name: BackasSurvivalPack-Extended
version: '${version}'
main: kr.kro.backas.backassurvivalpackextended.BackasSurvivalPackExtended
api-version: 1.20

commands:
  warp:
    description: 워프를 이용합니다.
    aliases: [워프, warps, dnjvm]
  ranking:
    description: 랭킹을 확인합니다.
    aliases: [rank, 랭킹, 랭크, fodzm, fodzld, top]
  money:
    description: 돈을 송금하거나 확인합니다.
    aliases: [돈, money, balance, bal, m, mny, ehs]
  money-admin:
    permission: op
    description: 돈을 관리합니다.
    aliases: [돈관리]
  sell:
    description: 상점을 엽니다.
    aliases: [판매, vksao]
  shop:
    description: 상점을 엽니다.
    aliases: [상점, 상점열기, 상점열어, 상점열어줘, tkdwja, tkdwjadufrl]
  item-admin:
    permission: op.op
  shop-list:
    aliases: [판매목록, 판매리스트, shoplist]
  tpa:
  tpaccept:
  tpadeny:
  tpahere:
  coin:
  point:
    description: 잠수 포인트를 확인합니다.
    aliases: [포인트, 잠수포인트, vhdlsxm]
  point-admin:
    permission: op
    description: 잠수 포인트를 관리합니다.
    aliases: [포인트관리]
  title:
    description: 칭호 상점을 엽니다.
    aliases: [칭호, 칭호상점, cldgh]
  farming:
    description: 농사 레벨을 확인합니다.
    aliases: [농사, 농사레벨, shdtk]
  mining:
    description: 광질 레벨을 확인합니다.
    aliases: [광질, 광질레벨, rhkdwlf]