name: BackasSurvivalPack-Extended
version: '${version}'
main: kr.kro.backas.backassurvivalpackextended.BackasSurvivalPackExtended
api-version: 1.20

commands:
  warp:
    description: 워프를 이용합니다.
    aliases: [워프, warps, dnjvm]
  ranking:
    description: 랭킹을 확인합니다.
    aliases: [rank, 랭킹, 랭크, fodzm, fodzld, top]
  money:
    description: 돈을 송금하거나 확인합니다.
    aliases: [돈, money, balance, bal, m, mny, ehs]
  money-admin:
    permission: op
    description: 돈을 관리합니다.
    aliases: [돈관리]
  sell:
    description: 상점을 엽니다.
    aliases: [판매, vksao]
  shop:
    description: 상점을 엽니다.
    aliases: [상점, 상점열기, 상점열어, 상점열어줘, tkdwja, tkdwjadufrl]
  item-admin:
    permission: op.op
  shop-list:
    aliases: [판매목록, 판매리스트, shoplist]
  tpa:
  tpaccept:
  tpadeny:
  tpahere: